### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kristianfoerster** [EdiSalazar/DWA-a102#3]
Dear EdiSalazar,

I would like to extend your DWA-a102 lib by adding methods to compute the local water balance. I just started using a fork but I was wondering if you have any plans regarding the license of your work? Thank you!

Best wishes,

Kristian

**Comment by EdiSalazar** [comment]
Dear Proffesor Förster,
it is nice to hear from you.
I have no interest in licensing that work. It was done for academic purposes and I am happy if it can serve anyone who needs it.
I hope this clarifies any doubts you can have.
Do not hesitate to contact me if you need something else.
All the best in your need academic path in the South.
Beste Grüße
Edwin

**Comment by kristianfoerster** [comment]
Dear Edwin,

Thank you for your prompt reply. I am glad to read from you and I really appreciate your work and I believe it's of great value for others. However, having no license means that "all rights are reserved" (see this dicussion https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license/1721#1721). In order to facilitate its reuse, an open source license could make sense (see, e.g., https://choosealicense.com/). If you give me the permission to proceed working on the repository in order to share it with students (as indicated in your reply), it's also fine (though a license is the best option in my opinion). In any case I'll keep you updated on that and maybe we could also merge the things later. We could also have a follow-up discussion on that if you wish. Thank you!

Best wishes,

Kristian

**Comment by EdiSalazar** [comment]
Dear Kristian,

I was not aware of that. Now I added the LICENSE file to the project.
The project now is under MIT License, which after a quick search is an easy and permissive one. I hope this one is right for your purposes. It would be great if you, your students or anyone can expand the actual work. I will be looking forward to seeing those works.

Best regards,

Edwin

**Comment by kristianfoerster** [comment]
Dear Edwin,

Thank you very much for taking the license into consideration. I think that the MIT License makes sense. We'll keep you informed!

Best wishes,

Kristian
